# Sets up a test environment for Linux/OSX and runs unit tests
steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: 'Add conda to PATH'

- bash: 'conda env create --quiet --file test-environment.yml python=$PYTHON_VERSION'
  displayName: 'Create Anaconda Environment'

- bash: |
    source activate test_environment
    pip install -e .
    pip install pytest pytest-azurepipelines pytest-cov
    pip install https://github.com/chstan/igorpy/tarball/712a4c4#egg=igor-0.3.1
  displayName: 'Install PyARPES, Igor, and Test Requirements'

- bash: 'source activate test_environment && pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=arpes --cov-report=xml --cov-report=html'
  displayName: 'pytest'