# Conda Build Artifacts and Upload

trigger:
- master
- release

pool:
  name: Hosted Ubuntu 1604
variables:
  python.version: '3.6'

steps:
- template: templates/unix-configure-conda-and-test.yml

- bash: |
    source activate root
    conda install -y conda-build anaconda-client
    python setup.py sdist
    python setup.py bdist_wheel
    mkdir "conda-dist"
    conda-build ./conda/ -c anaconda -c conda-forge --output-folder conda-dist
  displayName: 'conda-build'

- task: CopyFiles@2
  inputs:
    contents: conda-dist/**
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: PyARPES_Conda

- bash: |
    yes | anaconda login --username $(conda.user) --password $(conda.password)
    anaconda upload -u arpes conda-dist/noarch/$(ls conda-dist/noarch/ | grep ".tar.bz2")
  displayName: 'Upload to conda'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))

- bash: |
    pip install twine
    twine upload -u $(pypi.user) -p $(pypi.password) dist/*
  displayName: 'Upload to PyPI'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))